### ISSUE TITLE
Mismatch between GitHub, Git

### ISSUE THREAD

**Issue by wooorm** [DaveBitter/minor-webdev_real-time-web#19]
Commits you make on your computer aren’t associated with your GitHub account (resulting in those [broken images](https://github.com/DaveBitter/minor-webdev_real-time-web/commits/master)).

Probably fix: https://help.github.com/articles/setting-your-email-in-git/#setting-your-email-address-for-every-repository-on-your-computer.

**Comment by DaveBitter** [comment]
Thanks! I use Smartgit, the terminal and github al together. Why? Because I make no sense sometimes. From now on i'm using git from the command line only. I will also to the above mentioned fix
